osx_image: xcode9.4
language: objective-c
before_install:
    - chmod +x "./testCI/scripts/build.sh"
    - chmod +x "./testCI/scripts/add-key.sh"

before_script:
- "./testCI/scripts/add-key.sh"

env:
  global:
  - APP_NAME="testCI"
  - DEVELOPER_NAME="iPhone Distribution: EaseMob Inc."
  - PROFILE_NAME="testCI"

script:
- "./testCI/scripts/build.sh"
