osx_image: xcode9.4
language: objective-c 
before_install:
 - brew update
 - brew install xctool
env: 
global: 
- LANG=en_US.UTF-8 
- LC_ALL=en_US.UTF-8 

script:
- xcodebuild archive -project testCI/testCI.xcodeproj -scheme testCI -configuration Release -archivePath archive/testCI.xcarchive CODE_SIGN_IDENTITY="iPhone Developer"
- xcodebuild -exportArchive -archivePath archive/testCI.xcarchive -exportPath build  -exportOptionsPlist ./ExportOptions.plist



