osx_image: xcode9.4
language: objective-c 
before_install:
 "gem brew update"
env: 
global: 
- LANG=en_US.UTF-8 
- LC_ALL=en_US.UTF-8 

script:
- xcodebuild -project testCI.xcodeproj -target testCI -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO




